### ISSUE TITLE
Recommend set image-rendering to crisp-edges to optimize image sharpness for low PPI devices

### ISSUE THREAD

**Issue by WGzeyu** [beatmaps-io/beatsaver-main#26]
[https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering)
 ```css
img {
  image-rendering: -webkit-optimize-contrast;
  image-rendering: crisp-edges;
}
 ```
![](https://wgzeyu.gtxcn.com/img/bs/crisp-edges.png)
